# Generated by Django 5.1.5 on 2025-01-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0002_product_cart_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('income', models.IntegerField()),
                ('expenses', models.IntegerField()),
                ('harvested_quantity', models.IntegerField()),
                ('profit_loss', models.IntegerField()),
            ],
        ),
    ]
